## This file has been generated by regen.py
## Changes may be overwritten the next time 
## configs are re-generated

# Colors
# black
export foreground='#e4e4e5'
export background='#0E1115'

export base00='#171C21'
export base08='#949494'

# red
export base01='#f7467b'
export base09='#ff62a4'

# green
export base02='#1addb0'
export base10='#00ffb1'

# yellow
export base03='#ff8a30'
export base11='#FFC457'
 
# blue
export base04='#2798e4'
export base12='#53befc'

# magenta
export base05='#9554ff'
export base13='#B467F9'

# cyan
export base06='#2BCAFC'
export base14='#2bfcfc'

# white
export base07='#d4d4d5'
export base15='#ffffff'

# vim:filetype=zsh
