## This file has been generated by regen.py
## Changes may be overwritten the next time 
## configs are re-generated


export background='#101317'
export foreground='#dddddd'

# Black
export base00='#171b21'
export base08='#2d373e'

# Red
export base01='#f7467b'
export base09='#ff62c1'
         
# Green  
export base02='#00ffb1'
export base10='#1addb0'

# Yellow
export base03='#f99e44'
export base11='#ffc857'

# Blue
export base04='#53befc'
export base12='#2798e4'

# Magenta
export base05='#B467F9'
export base13='#9554ff'

# Cyan
export base06='#2bfcfc'
export base14='#2BCAFC'

# White
export base07='#8e8e8e'
export base15='#f2f4f5'

# vim:filetype=zsh
