-- Scrollbar
return {
  ScrollbarHandle = { bg = "one_bg2" },
  ScrollbarCursorHandle = { bg = "one_bg2", fg = "white" },
  ScrollbarCursor = { fg = "white" },
  ScrollbarSearchHandle = { bg = "one_bg2", fg = "green" },
  ScrollbarSearch = { fg = "green" },
  ScrollbarErrorHandle = { bg = "one_bg2", fg = "red" },
  ScrollbarError = { fg = "red" },
  ScrollbarWarnHandle = { bg = "one_bg2", fg = "orange" },
  ScrollbarWarn = { fg = "orange" },
  ScrollbarInfoHandle = { bg = "one_bg2", fg = "purple" },
  ScrollbarInfo = { fg = "purple" },
  ScrollbarHintHandle = { bg = "one_bg2", fg = "purple" },
  ScrollbarHint = { fg = "purple" },
  ScrollbarMiscHandle = { bg = "one_bg2", fg = "blue" },
  ScrollbarMisc = { fg = "blue" },
  ScrollbarGitAdd = { fg = "cyan" },
  ScrollbarGitAddHandle = { bg = "one_bg2", fg = "cyan" },
  ScrollbarGitChange = { fg = "cyan" },
  ScrollbarGitChangeHandle = { bg = "one_bg2", fg = "cyan" },
  ScrollbarGitDelete = { fg = "cyan" },
  ScrollbarGitDeleteHandle = { bg = "one_bg2", fg = "cyan" },
}
